programs:
  mmul:
    build_path: "./build"
repetitions: 5
measurement_program: 
  path: "/usr/bin/time"
  args: ["-v"] 
output:
  path: "./local"
lcc3: False
tile_min: 1
tile_bound: 2048
optuna_trials: 150    
optuna_warmup_reps: 3
converge: true           
cv_threshold: 0.05
max_reps: 20