programs:
  qap:
    build_path: "~/perf-oriented-dev/small_samples/build"
    args: 
      - ["/home/gregor/perf-oriented-dev/small_samples/qap/problems/chr15b.dat"]
  delannoy:
    build_path: "~/perf-oriented-dev/small_samples/build"
    args: 
      - [12]
  filegen:
    build_path: "~/perf-oriented-dev/small_samples/build"
    args:
      - [200, 200, 10, 1000]
  filesearch:
    build_path: "~/perf-oriented-dev/small_samples/build" 
  mmul:
    build_path: "~/perf-oriented-dev/small_samples/build"
    defines:
      - {S: 512}
  nbody:
    build_path: "~/perf-oriented-dev/small_samples/build"
    defines:
      - {N: 100, M: 200}
repetitions: 4
converge: True
measurement_program: 
  path: "/usr/bin/time"
  args: ["-v"] 
output:
  path: "~/perf-oriented-dev/solutions/exercise2/local_no_load"
lcc3: False